---
version: v0.0.0
time_zone: UTC
logging:
  logger: glg
  level: warn
  format: raw

server_config:
  servers:
    - name: grpc
      host: 0.0.0.0
      port: 8081
      grpc:
        bidirectional_stream_concurrency: 20
        connection_timeout: ""
        header_table_size: 0
        initial_conn_window_size: 2097152
        initial_window_size: 1048576
        interceptors: []
        keepalive:
          max_conn_age: ""
          max_conn_age_grace: ""
          max_conn_idle: ""
          time: 120s
          timeout: 30s
        max_header_list_size: 0
        max_receive_message_size: 0
        max_send_message_size: 0
        read_buffer_size: 0
        write_buffer_size: 0
      mode: GRPC
      probe_wait_time: 3s
      restart: true
  health_check_servers: []
  metrics_servers: []
  startup_strategy:
    - grpc
  full_shutdown_duration: 600s
  tls:
    enabled: false

ngt:
  # Index configuration
  auto_create_index_pool_size: 10000
  auto_index_check_duration: 1s
  auto_index_duration_limit: 1h
  auto_index_length: 10
  auto_save_index_duration: 35m
  bulk_insert_chunk_size: 10
  creation_edge_size: 20
  default_epsilon: 0.1
  default_pool_size: 10000
  default_radius: -1
  dimension: 384
  distance_type: l2
  enable_copy_on_write: false
  enable_in_memory_mode: true
  enable_proactive_gc: true
  index_path: /etc/server/backup
  initial_delay_max_duration: 3m
  load_index_timeout_factor: 1ms
  max_load_index_timeout: 10m
  min_load_index_timeout: 3m
  object_type: float
  search_edge_size: 10
  vqueue:
    delete_buffer_pool_size: 5000
    insert_buffer_pool_size: 10000
