metadata_dir = "/var/lib/garage/meta"
data_dir = "/var/lib/garage/data"
db_engine = "sqlite"

replication_mode = "none"
compression_level = 1

[rpc]
bind_addr = "[::]:3903"
secret = "00000000000000000000000000000000"

[s3_api]
s3_region = "garage"
api_bind_addr = "[::]:3900"
root_domain = ".s3.garage.localhost"

[s3_web]
bind_addr = "[::]:3901"
root_domain = ".web.garage.localhost"

[admin]
api_bind_addr = "[::]:3902"
admin_token = "admintoken"
