name = "mizu-search"
main = "src/index.ts"
compatibility_date = "2026-02-05"
compatibility_flags = ["nodejs_compat"]

[site]
bucket = "./static"

[[kv_namespaces]]
binding = "SEARCH_KV"
id = "3550c0440b6f4f30a49797935234965a"
preview_id = "c08cc94eb29c4dbfb5ef2d5f20654405"

[vars]
ENVIRONMENT = "production"
